apiVersion: apps.openshift.io/v1
kind: List
items:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: apiapp
      name: apidc1
    spec:
      replicas: 1
      selector:
        app: apiapp
        deploymentconfig: apidc1
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: apiapp
            deploymentconfig: apidc1
        spec:
          containers:
            - image: pkuma343/myimage:v1
              imagePullPolicy: Always
              name: apidc1
              ports:
                - containerPort: 8443
                  protocol: TCP
                - containerPort: 8080
                  protocol: TCP
              resources:
                limits:
                  cpu: 400m
                  memory: 500M
                requests:
                  cpu: 300m
                  memory: 300M
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /actuator/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 45
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              env:
                - name: JAVA_OPTS
                  value: "-Xms6G -Xmx6G"
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: apiapp
      name: apidc2
    spec:
      replicas: 1
      selector:
        app: apiapp
        deploymentconfig: apidc2
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: apiapp
            deploymentconfig: apidc2
        spec:
          containers:
            - image: pkuma343/myimage:v1
              imagePullPolicy: Always
              name: apidc2
              ports:
                - containerPort: 8443
                  protocol: TCP
                - containerPort: 8080
                  protocol: TCP
              resources:
                limits:
                  cpu: 400m
                  memory: 500M
                requests:
                  cpu: 300m
                  memory: 300M
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /actuator/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 45
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              env:
                - name: JAVA_OPTS
                  value: "-Xms6G -Xmx6G"
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
      labels:
        app: apiapp
      name: application-service
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: apiapp
        deploymentconfig: apidc2
      sessionAffinity: None
      type: ClusterIP